using UnityEngine;

public class Player_RayCast : MonoBehaviour
{
    [SerializeField] private float rayCastRange = 5f;
    [SerializeField] private LayerMask interactableLayer;
    [SerializeField] private Transform holdPosition;

    private HeldObject heldObject;

    void Update()
    {
        if (heldObject == null)
        {
            RaycastHit hit;
            if (Physics.Raycast(Camera.main.transform.position, Camera.main.transform.forward, out hit, rayCastRange, interactableLayer))
            {
                Debug.Log("Ray hit: " + hit.collider.gameObject.name); // Debug ekleyelim

                var hitObjectInteract = hit.collider.GetComponent<IInteractable>();
                if (hitObjectInteract != null && Input.GetKeyDown(KeyCode.E)) // E tuuna bas覺ld覺覺nda etkileim
                {
                    hitObjectInteract.interact(); // objeyi etkile
                }
            }
        }
        else
        {
            if (Input.GetKeyDown(KeyCode.E)) // E tuuna bas覺l覺nca objeyi b覺rak
            {
                heldObject.Drop();
                ClearHeldObject();
            }
        }
    }

    public void SetHeldObject(HeldObject obj)
    {
        heldObject = obj;
    }

    public void ClearHeldObject()
    {
        heldObject = null;
    }

    //  Eklenen k覺s覺m: Elimizdeki objeyi d覺ar覺dan alabilmek i癟in
    public HeldObject GetHeldObject()
    {
        return heldObject;
    }
}
